##=== Calbuco
#year = 2015
#doys = [112] # April 22, day of eruption
#sec = 75600 # 21:00 UTC, ~start of eruption
#=== PCCVC
year = 2011
doys = [155, 156] # June 4, day of eruption
sec = [0, 21600] # 00:00:00 UTC, 06:00:00 UTC...

hmin = 0.0 # km
hmax = 170.0 # km
dh = 0.5 # km

f107a = 150 # moderate solar activity
f107 = 150
apd = 4 # quiet geomagnetic activity
aph = 4


sou_pos = [
#    [-41.33, -72.62], # Calbuco
    [-40.59, -72.117] # PCCVC
]

sta_pos = [
#    [-40.7,	-70.6], # I01AR
#   [-54.6  , -67.3], #I02AR
#    [-16.2  , -68.5], #I08BO
#    [-15.6 , -48.0], #I09BR
#    [-27.1  , -109.4], #I13CL
#    [-33.7  , -78.8], #I14CL
#    [-70.7   , -8.3], #I27DE
    [-26.3  , -57.3], #I41PY
#    [-37.1  , -12.3] #I49GB
]

sta_nam = [ 
#    "IS01",
#   "IS02",
#    "IS08",
#    "IS09",
#    "IS13",
#    "IS14",
#    "IS27",
    "IS41",
#    "IS49"
]

sta_skp = [
#    3, # IS13
#    2, # IS14
    ]

ds = 50.0 # km

# If using RngDep
[range_dependent]
use_rng_dep = true
recycle = true
dlat = 0.25
dlon = 0.25

[ecmwf]
use_ecmwf = true
auto_area = true
min_lon = -110 # to define area for grid
max_lon = -10
min_lat = -80
max_lat = 0
dlon = 1.0  # grid step in degrees
dlat = 1.0
h1 = 60.0 # km, heights to start and end merge
h2 = 80.0
